name: Update Major Version Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Run on tags matching a semver

jobs:
  update-majorver:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@v1
